const COLORS = {
    BACKGROUND_PRIMARY: "#EAF6FF",
    FONTCOLOR_PRIMARY: "#232528",
    FONTCOLOR_SECONDARY: "#ACB0BD",
    CHECKED: "#2C5530",
    DELETE:"#C1292E",
    WHITE:"#FDFFFC"
}

export default COLORS;